[package]
name = "paperasse-privacy-python"
description = "Python bindings for paperasse-privacy"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lib]
name = "paperasse_privacy"
crate-type = ["cdylib"]

[dependencies]
paperasse-privacy-core = { workspace = true }
pyo3 = { version = "0.23", features = ["extension-module"] }
pyo3-async-runtimes = { version = "0.23", features = ["tokio-runtime"] }
tokio = { workspace = true, features = ["rt-multi-thread"] }
