/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Presidio NER pass configuration — the opt-in "Tier B". When present,
 * detection runs the local recognizers *and* a Presidio `/analyze` call,
 * with Presidio's spans routed through the same OCR word boxes the local
 * recognizers use, so a PERSON found on a photographed letter gets a real
 * black box on the image.
 *
 * Two behaviours worth knowing before turning it on:
 *
 * * **Fail-closed, twice.** If the analyzer is unreachable, redaction
 *   errors rather than quietly returning a result missing every name it
 *   was asked to catch. And if a Presidio span can't be matched to any
 *   OCR word box on a pixel output, the whole run errors naming the
 *   entity types that would have been silently visible.
 * * **Your text goes to that URL.** Point this at an analyzer *you* run
 *   (localhost or your own network). Nothing in this library ever picks a
 *   remote endpoint on its own.
 */
export interface TierBOptions {
  /** Base URL of a running presidio-analyzer, e.g. `http://localhost:5002`. */
  analyzerUrl: string
  /**
   * Language code Presidio should analyze with (e.g. `"fr"`, `"en"`).
   * Defaults to `"en"` — the stock analyzer image only loads English;
   * French needs an analyzer configured with a French NLP model.
   */
  language?: string
}
/** Options for `redactText`. All fields optional. */
export interface RedactTextOptions {
  /**
   * Structured markdown output is the default (this is a tool for
   * agents, and markdown is what they parse best) — pass `false` to get
   * back plain text in the input's own shape instead.
   */
  markdown?: boolean
  /**
   * Only redact these entity types (e.g. `["FR_NIR"]`) — matches
   * Presidio's `analyzer_entities` filter. Omit/undefined to redact
   * every entity type Tier A's recognizers cover.
   */
  entities?: Array<string>
  /**
   * Drop matches scoring below this (0.0-1.0). Matches Presidio's
   * `score_threshold`. Omit/undefined for no filtering.
   */
  scoreThreshold?: number
  /**
   * Run a Presidio NER pass alongside the local recognizers — see
   * `TierBOptions` for the two fail-closed behaviours this brings.
   */
  tierB?: TierBOptions
}
/**
 * Options for `redactImage`/`redactPdf`/`redactImageText`/`redactPdfText`.
 * Same filters as `RedactTextOptions` minus `markdown`: `redactImage`/
 * `redactPdf` always return pixel-redacted bytes (no markdown/native
 * choice — that's the point of calling them specifically), and
 * `redactImageText`/`redactPdfText` always return OCR'd redacted text
 * (there's no meaningful "native" alternative to toggle to for those --
 * `OutputFormat::Native` means pixel bytes for an image/PDF input, not
 * plain text, so a `markdown` flag here would be misleading).
 */
export interface RedactBytesOptions {
  /**
   * Only redact these entity types (e.g. `["FR_NIR"]`) — matches
   * Presidio's `analyzer_entities` filter. Omit/undefined to redact
   * every entity type Tier A's recognizers cover.
   */
  entities?: Array<string>
  /**
   * Drop matches scoring below this (0.0-1.0). Matches Presidio's
   * `score_threshold`. Omit/undefined for no filtering.
   */
  scoreThreshold?: number
  /**
   * Run a Presidio NER pass alongside the local recognizers — see
   * `TierBOptions` for the two fail-closed behaviours this brings.
   */
  tierB?: TierBOptions
}
/**
 * Redact PII from plain text — the fastest path (Tier A, in-process, no
 * network).
 */
export declare function redactText(text: string, options?: RedactTextOptions | undefined | null): Promise<string>
/**
 * Redact PII from a plain image (jpg/png/…): OCR it (liteparse, bundled
 * Tesseract or a configured HTTP OCR server), find PII in the OCR'd text
 * via Tier A, and black out each match's bounding box directly on the
 * original pixels. Returns the redacted image bytes, same format as the
 * input. Verified against a real photographed document — see the repo
 * README's "Build status" section.
 */
export declare function redactImage(bytes: Buffer, options?: RedactBytesOptions | undefined | null): Promise<Buffer>
/**
 * Redact PII from a PDF: render every page (liteparse/PDFium), find PII
 * via OCR + Tier A, black out matches, and reassemble a new PDF from the
 * redacted page images (`printpdf`). Deliberately flattens to an
 * image-based PDF — see `redact_pdf_bytes`'s doc comment in
 * `redact-paperasse-core` for why that's the correct behavior for
 * genuine redaction, not a limitation. Verified against a real document
 * embedded in a PDF — see the repo README's "Build status" section.
 *
 * Not available in the WASM binding: liteparse's PDF-to-raster rendering
 * doesn't exist in its wasm32 build (an upstream constraint).
 */
export declare function redactPdf(bytes: Buffer, options?: RedactBytesOptions | undefined | null): Promise<Buffer>
/**
 * Redact PII from a plain image (jpg/png/…) and return the OCR'd redacted
 * text directly — no pixel step. `Engine::process`'s `OutputFormat::Markdown`
 * branch runs before the input-type match, so this OCRs via liteparse,
 * finds PII in the OCR'd text via Tier A, and returns the redacted result
 * as text, skipping the bounding-box/pixel-drawing work `redactImage` does.
 * Cheaper than `redactImage` when an agent only needs the text content,
 * not a redacted image to display.
 */
export declare function redactImageText(bytes: Buffer, options?: RedactBytesOptions | undefined | null): Promise<string>
/**
 * Redact PII from a PDF and return the OCR'd redacted text directly — no
 * pixel step, no page-image reassembly. Same reasoning as
 * `redactImageText`: `OutputFormat::Markdown` short-circuits
 * `Engine::process` before it reaches the pixel-redaction path.
 *
 * Not available in the WASM binding, same constraint as `redactPdf`.
 */
export declare function redactPdfText(bytes: Buffer, options?: RedactBytesOptions | undefined | null): Promise<string>
