/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options for `redactText`. All fields optional. */
export interface RedactTextOptions {
  /**
   * Structured markdown output is the default (this is a tool for
   * agents, and markdown is what they parse best) — pass `false` to get
   * back plain text in the input's own shape instead.
   */
  markdown?: boolean
  /**
   * Only redact these entity types (e.g. `["FR_NIR"]`) — matches
   * Presidio's `analyzer_entities` filter. Omit/undefined to redact
   * every entity type Tier A's recognizers cover.
   */
  entities?: Array<string>
  /**
   * Drop matches scoring below this (0.0-1.0). Matches Presidio's
   * `score_threshold`. Omit/undefined for no filtering.
   */
  scoreThreshold?: number
}
/**
 * Options for `redactImage`/`redactPdf`. Same filters as `RedactTextOptions`
 * minus `markdown` — these two always return pixel-redacted bytes (that's
 * the point of calling them specifically); OCR'd-and-redacted markdown
 * text from an image/PDF isn't exposed at this binding layer yet.
 */
export interface RedactBytesOptions {
  /**
   * Only redact these entity types (e.g. `["FR_NIR"]`) — matches
   * Presidio's `analyzer_entities` filter. Omit/undefined to redact
   * every entity type Tier A's recognizers cover.
   */
  entities?: Array<string>
  /**
   * Drop matches scoring below this (0.0-1.0). Matches Presidio's
   * `score_threshold`. Omit/undefined for no filtering.
   */
  scoreThreshold?: number
}
/**
 * Redact PII from plain text — the fastest path (Tier A, in-process, no
 * network).
 */
export declare function redactText(text: string, options?: RedactTextOptions | undefined | null): Promise<string>
/**
 * Redact PII from a plain image (jpg/png/…): OCR it (liteparse, bundled
 * Tesseract or a configured HTTP OCR server), find PII in the OCR'd text
 * via Tier A, and black out each match's bounding box directly on the
 * original pixels. Returns the redacted image bytes, same format as the
 * input. Verified against a real photographed document — see the repo
 * README's "Build status" section.
 */
export declare function redactImage(bytes: Buffer, options?: RedactBytesOptions | undefined | null): Promise<Buffer>
/**
 * Redact PII from a PDF: render every page (liteparse/PDFium), find PII
 * via OCR + Tier A, black out matches, and reassemble a new PDF from the
 * redacted page images (`printpdf`). Deliberately flattens to an
 * image-based PDF — see `redact_pdf_bytes`'s doc comment in
 * `redact-paperasse-core` for why that's the correct behavior for
 * genuine redaction, not a limitation. Verified against a real document
 * embedded in a PDF — see the repo README's "Build status" section.
 *
 * Not available in the WASM binding: liteparse's PDF-to-raster rendering
 * doesn't exist in its wasm32 build (an upstream constraint).
 */
export declare function redactPdf(bytes: Buffer, options?: RedactBytesOptions | undefined | null): Promise<Buffer>
